apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: sandbox-router-hc
  namespace: default
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: sandbox-router-svc
